"""remove salt column

Revision ID: 2d0b809603d3
Revises: a28f3c019905
Create Date: 2024-01-23 13:15:55.529411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0b809603d3'
down_revision = 'a28f3c019905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
